import { MenuItem, RestaurantSettings, Category, HeroConfig, Promotion, FeaturedItem, Banner, LandingPageConfig } from './types'

export const sampleCategories: Category[] = [
  { id: 'cat-1', name: 'Burgers', description: 'Juicy burgers made with premium ingredients', displayOrder: 1, active: true },
  { id: 'cat-2', name: 'Salads', description: 'Fresh, healthy salads and bowls', displayOrder: 2, active: true },
  { id: 'cat-3', name: 'Pizza', description: 'Hand-tossed pizzas with authentic flavors', displayOrder: 3, active: true },
  { id: 'cat-4', name: 'Sushi', description: 'Fresh sushi rolls and sashimi', displayOrder: 4, active: true },
  { id: 'cat-5', name: 'Pasta', description: 'Traditional Italian pasta dishes', displayOrder: 5, active: true },
  { id: 'cat-6', name: 'Bowls', description: 'Nourishing grain and protein bowls', displayOrder: 6, active: true },
  { id: 'cat-7', name: 'Tacos', description: 'Authentic street-style tacos', displayOrder: 7, active: true },
  { id: 'cat-8', name: 'Indian', description: 'Aromatic curries and traditional Indian cuisine', displayOrder: 8, active: true },
  { id: 'cat-9', name: 'Grill', description: 'BBQ and grilled specialties', displayOrder: 9, active: true },
  { id: 'cat-10', name: 'Desserts', description: 'Sweet treats and indulgent desserts', displayOrder: 10, active: true },
  { id: 'cat-11', name: 'Soups', description: 'Warming soups and broths', displayOrder: 11, active: true },
]

export const sampleMenuItems: MenuItem[] = [
  {
    id: '1',
    name: 'Classic Cheeseburger',
    description: 'Angus beef patty with aged cheddar, lettuce, tomato, and special sauce on a brioche bun',
    price: 14.99,
    categoryId: 'cat-1',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&h=400&fit=crop',
    dietaryTags: [],
    available: true,
  },
  {
    id: '2',
    name: 'Grilled Chicken Caesar',
    description: 'Romaine lettuce, grilled chicken, parmesan, croutons, and house-made Caesar dressing',
    price: 13.99,
    categoryId: 'cat-2',
    image: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=500&h=400&fit=crop',
    dietaryTags: ['Gluten-Free Option'],
    available: true,
  },
  {
    id: '3',
    name: 'Margherita Pizza',
    description: 'Fresh mozzarella, tomato sauce, basil, and extra virgin olive oil on hand-tossed dough',
    price: 16.99,
    categoryId: 'cat-3',
    image: 'https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=500&h=400&fit=crop',
    dietaryTags: ['Vegetarian'],
    available: true,
  },
  {
    id: '4',
    name: 'Spicy Tuna Roll',
    description: 'Fresh tuna, spicy mayo, cucumber, and avocado rolled in sushi rice and nori',
    price: 12.99,
    categoryId: 'cat-4',
    image: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=500&h=400&fit=crop',
    dietaryTags: ['Gluten-Free'],
    available: true,
  },
  {
    id: '5',
    name: 'Pasta Carbonara',
    description: 'Creamy sauce with pancetta, parmesan, and black pepper over fresh fettuccine',
    price: 15.99,
    categoryId: 'cat-5',
    image: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=500&h=400&fit=crop',
    dietaryTags: [],
    available: true,
  },
  {
    id: '6',
    name: 'Vegan Buddha Bowl',
    description: 'Quinoa, roasted chickpeas, avocado, kale, sweet potato, and tahini dressing',
    price: 13.99,
    categoryId: 'cat-6',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=400&fit=crop',
    dietaryTags: ['Vegan', 'Gluten-Free'],
    available: true,
  },
  {
    id: '7',
    name: 'Fish Tacos',
    description: 'Beer-battered cod, cabbage slaw, pico de gallo, and chipotle aioli in soft tortillas',
    price: 14.99,
    categoryId: 'cat-7',
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=500&h=400&fit=crop',
    dietaryTags: [],
    available: true,
  },
  {
    id: '8',
    name: 'Chicken Tikka Masala',
    description: 'Tender chicken in creamy tomato curry sauce served with basmati rice and naan',
    price: 16.99,
    categoryId: 'cat-8',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=500&h=400&fit=crop',
    dietaryTags: ['Gluten-Free Option'],
    available: true,
  },
  {
    id: '9',
    name: 'BBQ Ribs',
    description: 'Fall-off-the-bone pork ribs with house BBQ sauce, coleslaw, and fries',
    price: 22.99,
    categoryId: 'cat-9',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=500&h=400&fit=crop',
    dietaryTags: [],
    available: true,
  },
  {
    id: '10',
    name: 'Chocolate Lava Cake',
    description: 'Warm chocolate cake with molten center, vanilla ice cream, and berry compote',
    price: 8.99,
    categoryId: 'cat-10',
    image: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=500&h=400&fit=crop',
    dietaryTags: ['Vegetarian'],
    available: true,
  },
  {
    id: '11',
    name: 'Greek Salad',
    description: 'Tomatoes, cucumber, red onion, kalamata olives, feta cheese, and oregano dressing',
    price: 11.99,
    categoryId: 'cat-2',
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=500&h=400&fit=crop',
    dietaryTags: ['Vegetarian', 'Gluten-Free'],
    available: true,
  },
  {
    id: '12',
    name: 'Beef Pho',
    description: 'Vietnamese noodle soup with beef, rice noodles, herbs, and aromatic broth',
    price: 14.99,
    categoryId: 'cat-11',
    image: 'https://images.unsplash.com/photo-1591814468924-caf88d1232e1?w=500&h=400&fit=crop',
    dietaryTags: ['Gluten-Free'],
    available: true,
  },
]

export const defaultRestaurantSettings: RestaurantSettings = {
  name: 'Bistro Bay',
  phone: '(555) 123-4567',
  email: 'hello@bistrobay.com',
  address: '123 Harbor Street, San Francisco, CA 94102',
  hours: {
    monday: { open: '11:00', close: '22:00', closed: false },
    tuesday: { open: '11:00', close: '22:00', closed: false },
    wednesday: { open: '11:00', close: '22:00', closed: false },
    thursday: { open: '11:00', close: '22:00', closed: false },
    friday: { open: '11:00', close: '23:00', closed: false },
    saturday: { open: '10:00', close: '23:00', closed: false },
    sunday: { open: '10:00', close: '21:00', closed: false },
  },
  deliveryFee: 4.99,
  minimumOrder: 15,
  taxRate: 0.0875,
}

// Landing Page Defaults

export const defaultHeroConfig: HeroConfig = {
  id: 'hero-default',
  title: 'Welcome to Bistro Bay',
  subtitle: 'Fresh ingredients, made with love',
  tagline: 'Order online for pickup or delivery',
  backgroundImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1920&h=600&fit=crop',
  ctaText: 'View Our Menu',
  ctaLink: 'menu',
  overlayOpacity: 50,
  textAlignment: 'center',
  active: true,
}

export const defaultLandingPageConfig: LandingPageConfig = {
  showHero: true,
  showPromotions: true,
  showFeaturedItems: true,
  showBanners: true,
  promotionsTitle: 'Special Offers',
  featuredItemsTitle: "Chef's Picks",
}

export const samplePromotions: Promotion[] = [
  {
    id: 'promo-1',
    title: 'Weekend Pasta Special',
    description: 'Get 20% off all pasta dishes every Saturday and Sunday',
    discountType: 'percentage',
    discountValue: 20,
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=500&h=300&fit=crop',
    badgeText: '20% OFF',
    linkedCategoryId: 'cat-5',
    active: true,
    displayOrder: 1,
  },
  {
    id: 'promo-2',
    title: 'Free Dessert Friday',
    description: 'Free chocolate lava cake with any order over $30',
    discountType: 'freeItem',
    discountValue: 0,
    image: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=500&h=300&fit=crop',
    badgeText: 'FREE DESSERT',
    linkedCategoryId: 'cat-10',
    active: true,
    displayOrder: 2,
  },
  {
    id: 'promo-3',
    title: 'Lunch Combo Deal',
    description: '$5 off when you order a burger and salad combo',
    discountType: 'fixed',
    discountValue: 5,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&h=300&fit=crop',
    badgeText: '$5 OFF',
    active: true,
    displayOrder: 3,
  },
]

export const sampleFeaturedItems: FeaturedItem[] = [
  {
    id: 'feat-1',
    menuItemId: '1',
    badgeText: 'Most Popular',
    displayOrder: 1,
    active: true,
  },
  {
    id: 'feat-2',
    menuItemId: '3',
    badgeText: "Chef's Special",
    displayOrder: 2,
    active: true,
  },
  {
    id: 'feat-3',
    menuItemId: '8',
    badgeText: 'Customer Favorite',
    displayOrder: 3,
    active: true,
  },
  {
    id: 'feat-4',
    menuItemId: '6',
    badgeText: 'Healthy Choice',
    displayOrder: 4,
    active: true,
  },
]

export const sampleBanners: Banner[] = [
  {
    id: 'banner-1',
    title: 'Free Delivery on Orders Over $40',
    subtitle: 'Limited time offer - Order now!',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1200&h=400&fit=crop',
    linkType: 'menu',
    linkValue: '',
    position: 'top',
    size: 'medium',
    textColor: 'light',
    active: true,
    displayOrder: 1,
  },
  {
    id: 'banner-2',
    title: 'Try Our New Sushi Menu',
    subtitle: 'Fresh rolls made daily by our master chef',
    image: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=1200&h=400&fit=crop',
    linkType: 'category',
    linkValue: 'cat-4',
    position: 'middle',
    size: 'large',
    textColor: 'light',
    active: true,
    displayOrder: 1,
  },
]
